version: 2.1
workflows:
  testing:
    jobs:
      - runner-test

runner:
  ssh:
    advertise_addr: brent-katie-docker-test-runner:54782

jobs:
  runner-test:
    machine: true
    resource_class: brentmmarks/docker-runner
    steps:
      - checkout
      - run: npm install
      - run: node index.js
