version: 2.1
workflows:
  testing:
    jobs:
      - runner-test

runner:
  cleanup_working_directory: true

jobs:
  runner-test:
    machine: true
    resource_class: brentmmarks/docker-runner
    steps:
      - checkout
      - run: pwd && ls
      - run: npm install
      - run: node index.js
