version: 2.1
workflows:
  testing:
    jobs:
      - runner-test

jobs:
  runner-test:
    machine: true
    resource_class: brentmmarks/docker-runner
    steps:
      - checkout
      - run: npm install
      - run: node index.js
