version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
      - machine-test

parameters:
  debug:
    type: boolean
    default: false

jobs:
  machine-test:
    machine: true
    resource_class: large
    steps:
      - checkout
      - run: npm install
      - run: node index.js
  runner-test:
    machine: true
    resource_class: brentmmarks/docker-runner
    environment:
      - DEBUG_DOCKER_OUTPUT: << pipeline.parameters.debug >>
    steps:
      - checkout
      - run: npm install
      - run: node index.js
