version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
      - machine-test

jobs:
  machine-test:
    machine: true
    resource_class: large
    steps:
      - checkout
      - run: ls -la
      - run: |
          npm install
          node index.js
  runner-test:
    machine: true
    resource_class: brentmmarks/docker-runner
    steps:
      - checkout
      - run: ls -la
      - run: npm install
      - run: node index.js
